export const SCHEMA_KEY = Symbol('SCHEMA_KEY_PROPERTY_METADATA');
export const CHECKER_FUNCTION = Symbol('CHECKER_FUNCTION');
export const OPENAPI_META_KEY_PROPERTY = Symbol('OPENAPI_META_KEY_PROPERTY');
export const OPENAPI_META_KEY_CLASS = Symbol('OPENAPI_META_KEY_CLASS');
export const OPENAPI_META_TARGET = {
  ['OPENAPI_META_TARGET']: Symbol('OPENAPI_META_TARGET'),
};
