-- AlterTable
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "league" TEXT;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "score_a" INTEGER;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "score_b" INTEGER;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "best_of" INTEGER;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "betting_open_until" TIMESTAMP(3);
